-- Append-only history of status changes, written in the same transaction as the change itself.
CREATE TABLE payment_audit (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_id  UUID         NOT NULL REFERENCES payment (id),
    from_status VARCHAR(20)  NOT NULL,
    to_status   VARCHAR(20)  NOT NULL,
    occurred_at TIMESTAMPTZ  NOT NULL
);
