-- Events waiting to be published (docs/episodes/bonus-03). A row is written in the same transaction as the
-- status change it describes; PaymentEventRelay sends it to Kafka later and sets published_at.
-- The id is the publish order. The row holds the event, not the Kafka message: the relay owns the wire format.
CREATE TABLE payment_outbox (
    id                     BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id               UUID           NOT NULL UNIQUE,
    event_type             VARCHAR(40)    NOT NULL,
    payment_id             UUID           NOT NULL REFERENCES payment (id),
    source_account_id      VARCHAR(64)    NOT NULL,
    destination_account_id VARCHAR(64)    NOT NULL,
    amount                 NUMERIC(19, 2) NOT NULL,
    currency               VARCHAR(3)     NOT NULL,
    occurred_at            TIMESTAMPTZ    NOT NULL,
    published_at           TIMESTAMPTZ
);

-- The relay only ever looks for unpublished rows, oldest first; published ones drop out of the index.
CREATE INDEX payment_outbox_unpublished ON payment_outbox (id) WHERE published_at IS NULL;
