-- Refunds (docs/episodes/bonus-04). Each row is one money movement back to the payer, with its own lifecycle.
-- idempotency_key is the customer-scoped, hashed Idempotency-Key that created it. UNIQUE, so the insert claims the key.
CREATE TABLE refund (
    id                UUID           PRIMARY KEY,
    payment_id        UUID           NOT NULL REFERENCES payment (id),
    amount            NUMERIC(19, 2) NOT NULL CHECK (amount > 0),
    currency          VARCHAR(3)     NOT NULL,
    status            VARCHAR(20)    NOT NULL,
    idempotency_key   VARCHAR(255)   NOT NULL UNIQUE,
    created_at        TIMESTAMPTZ    NOT NULL,
    status_changed_at TIMESTAMPTZ    NOT NULL
);

CREATE INDEX refund_payment_id ON refund (payment_id);

-- As payment_audit. from_status is null for the row that records the refund's creation.
CREATE TABLE refund_audit (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    refund_id   UUID         NOT NULL REFERENCES refund (id),
    from_status VARCHAR(20),
    to_status   VARCHAR(20)  NOT NULL,
    occurred_at TIMESTAMPTZ  NOT NULL
);

-- A refund's events name the refund; a payment's own events leave it null.
ALTER TABLE payment_outbox ADD COLUMN refund_id UUID REFERENCES refund (id);
